In [1]:
import json
from pathlib import Path

filepath = Path("wandb_final_scorers/scorers-ho-heavy-backbone/results.json")

with filepath.open("r") as f:
    data = json.load(f)

len(data)

15

In [2]:
list(data.keys())

["banking77[seed='42']",
 "minds14[seed='42']",
 "hwu64[seed='42']",
 "massive[seed='42']",
 "banking77[seed='43']",
 "minds14[seed='43']",
 "hwu64[seed='43']",
 "massive[seed='43']",
 "banking77[seed='44']",
 "minds14[seed='44']",
 "hwu64[seed='44']",
 "massive[seed='44']",
 "snips[seed='42']",
 "snips[seed='43']",
 "snips[seed='44']"]

In [3]:
data["banking77[seed='44']"]

[{'module_name': 'final_metrics',
  'config': {'value': {'decision_accuracy': 0.9301948051948052,
    'decision_f1': 0.9301431511050137,
    'decision_precision': 0.9339972057445086,
    'decision_recall': 0.9301948051948056,
    'decision_roc_auc': 0.9646381578947368}}}]

In [4]:
def extract_dataset_and_seed(key):
    """
    Extract dataset name and seed from a string like "banking77[seed='44']"
    
    Args:
        key (str): String in format "dataset_name[seed='seed_value']"
        
    Returns:
        tuple: (dataset_name, seed_value)
    """
    import re
    
    # Use regex to extract dataset name and seed value
    match = re.match(r"([^[]+)\[seed='(\d+)'\]", key)
    
    if match:
        dataset_name = match.group(1)
        seed = match.group(2)
        return dataset_name, seed
    else:
        return None, None

In [5]:
from collections import defaultdict
grouped_res = defaultdict(list)

for group, res in data.items():
    dataset, seed = extract_dataset_and_seed(group)
    grouped_res[dataset].append(res[0]["config"]["value"])

In [6]:
grouped_res

defaultdict(list,
            {'banking77': [{'decision_accuracy': 0.9256493506493506,
               'decision_f1': 0.9258010408032752,
               'decision_precision': 0.9287298315949438,
               'decision_recall': 0.9256493506493509,
               'decision_roc_auc': 0.9623355263157897},
              {'decision_accuracy': 0.9298701298701298,
               'decision_f1': 0.9298708205089007,
               'decision_precision': 0.9338653933914957,
               'decision_recall': 0.9298701298701298,
               'decision_roc_auc': 0.9644736842105264},
              {'decision_accuracy': 0.9301948051948052,
               'decision_f1': 0.9301431511050137,
               'decision_precision': 0.9339972057445086,
               'decision_recall': 0.9301948051948056,
               'decision_roc_auc': 0.9646381578947368}],
             'minds14': [{'decision_accuracy': 0.9351851851851852,
               'decision_f1': 0.9262380550306247,
               'decision_precision': 0.9540140415140416,
               'decision_recall': 0.9285714285714286,
               'decision_roc_auc': 0.9617712128355693},
              {'decision_accuracy': 0.9722222222222222,
               'decision_f1': 0.9682387787650946,
               'decision_precision': 0.9767857142857144,
               'decision_recall': 0.9693877551020408,
               'decision_roc_auc': 0.9836187700402694},
              {'decision_accuracy': 0.9629629629629629,
               'decision_f1': 0.9570978041566277,
               'decision_precision': 0.9662698412698413,
               'decision_recall': 0.9591836734693878,
               'decision_roc_auc': 0.9781703374419075}],
             'hwu64': [{'decision_accuracy': 0.9052044609665427,
               'decision_f1': 0.9035052307408895,
               'decision_precision': 0.9065762095354476,
               'decision_recall': 0.9041982962213225,
               'decision_roc_auc': 0.951346007660141},
              {'decision_accuracy': 0.9061338289962825,
               'decision_f1': 0.903918134861663,
               'decision_precision': 0.9054489784670916,
               'decision_recall': 0.9080268780926675,
               'decision_roc_auc': 0.9532678070376142},
              {'decision_accuracy': 0.9135687732342007,
               'decision_f1': 0.9131120915902263,
               'decision_precision': 0.9132792599235131,
               'decision_recall': 0.918080332040036,
               'decision_roc_auc': 0.9583536561295394}],
             'massive': [{'decision_accuracy': 0.8712938005390836,
               'decision_f1': 0.8596209008538767,
               'decision_precision': 0.88400971535979,
               'decision_recall': 0.8527057278055246,
               'decision_roc_auc': 0.9251997508533086},
              {'decision_accuracy': 0.8706199460916442,
               'decision_f1': 0.8590850819395164,
               'decision_precision': 0.8820433873590541,
               'decision_recall': 0.8519048680993739,
               'decision_roc_auc': 0.9247927757367207},
              {'decision_accuracy': 0.871967654986523,
               'decision_f1': 0.8566583980253625,
               'decision_precision': 0.8808429995357145,
               'decision_recall': 0.8550328231445132,
               'decision_roc_auc': 0.9263687941990221}],
             'snips': [{'decision_accuracy': 0.9885714285714285,
               'decision_f1': 0.9885848919953524,
               'decision_precision': 0.9887019324680795,
               'decision_recall': 0.9885714285714287,
               'decision_roc_auc': 0.9933333333333333},
              {'decision_accuracy': 0.9785714285714285,
               'decision_f1': 0.9785432576062247,
               'decision_precision': 0.9786927683579872,
               'decision_recall': 0.9785714285714285,
               'decision_roc_auc': 0.9874999999999999},
              {'decision_accuracy': 0.9785714285714285,
               'decision_f1': 0.9785292783128844,
               'decision_precision': 0.9786271182226137,
               'decision_recall': 0.9785714285714285,
               'decision_roc_auc': 0.9874999999999999}]})

In [7]:
rows = []
for dataset, metrics_dicts in grouped_res.items():
    metrics_list = defaultdict(list)
    for metrics_dict in metrics_dicts:
        for metric, value in metrics_dict.items():
            metrics_list[metric].append(value)
    mean_metrics = {metric: sum(values) / len(values) for metric, values in metrics_list.items()}
    rows.append({
        "dataset": dataset,
        **mean_metrics
    })
rows

[{'dataset': 'banking77',
  'decision_accuracy': 0.9285714285714285,
  'decision_f1': 0.9286050041390631,
  'decision_precision': 0.9321974769103161,
  'decision_recall': 0.9285714285714288,
  'decision_roc_auc': 0.9638157894736844},
 {'dataset': 'minds14',
  'decision_accuracy': 0.95679012345679,
  'decision_f1': 0.9505248793174491,
  'decision_precision': 0.9656898656898658,
  'decision_recall': 0.9523809523809524,
  'decision_roc_auc': 0.974520106772582},
 {'dataset': 'hwu64',
  'decision_accuracy': 0.9083023543990086,
  'decision_f1': 0.9068451523975929,
  'decision_precision': 0.9084348159753507,
  'decision_recall': 0.9101018354513419,
  'decision_roc_auc': 0.9543224902757649},
 {'dataset': 'massive',
  'decision_accuracy': 0.8712938005390836,
  'decision_f1': 0.8584547936062519,
  'decision_precision': 0.8822987007515195,
  'decision_recall': 0.8532144730164705,
  'decision_roc_auc': 0.9254537735963505},
 {'dataset': 'snips',
  'decision_accuracy': 0.981904761904762,
  'decision_f1': 0.9818858093048205,
  'decision_precision': 0.9820072730162268,
  'decision_recall': 0.981904761904762,
  'decision_roc_auc': 0.9894444444444445}]

In [8]:
import pandas as pd

df = pd.DataFrame(rows)
df

,dataset,decision_accuracy,decision_f1,decision_precision,decision_recall,decision_roc_auc
0,banking77,0.928571,0.928605,0.932197,0.928571,0.963816
1,minds14,0.956790,0.950525,0.965690,0.952381,0.974520
2,hwu64,0.908302,0.906845,0.908435,0.910102,0.954322
3,massive,0.871294,0.858455,0.882299,0.853214,0.925454
4,snips,0.981905,0.981886,0.982007,0.981905,0.989444

In [9]:
pd.set_option("display.precision", 2)

In [10]:
df * 100

,dataset,decision_accuracy,decision_f1,decision_precision,decision_recall,decision_roc_auc
0,banking77banking77banking77banking77banking77b...,92.86,92.86,93.22,92.86,96.38
1,minds14minds14minds14minds14minds14minds14mind...,95.68,95.05,96.57,95.24,97.45
2,hwu64hwu64hwu64hwu64hwu64hwu64hwu64hwu64hwu64h...,90.83,90.68,90.84,91.01,95.43
3,massivemassivemassivemassivemassivemassivemass...,87.13,85.85,88.23,85.32,92.55
4,snipssnipssnipssnipssnipssnipssnipssnipssnipss...,98.19,98.19,98.20,98.19,98.94