In [2]:
import json
from pathlib import Path

filepath = Path("wandb_encoders/autointent_encoders2/results.json")

with filepath.open("r") as f:
    data = json.load(f)

len(data)

25

In [3]:
metric_name = "decision_accuracy"

In [4]:
def transform_record(rec):
    rec["metrics"] = rec["metrics"][metric_name]
    return rec

In [5]:
import pandas as pd

df = pd.DataFrame([transform_record(rec) for rec in data])
df.head()

               dataset                                      encoder   metrics
0  DeepPavlov/clinc150               intfloat/multilingual-e5-large  0.787091
1  DeepPavlov/clinc150      intfloat/multilingual-e5-large-instruct  0.789818
2  DeepPavlov/clinc150  HIT-TMG/KaLM-embedding-multilingual-mini-v1  0.788545
3  DeepPavlov/clinc150                 NovaSearch/stella_en_400M_v5  0.918000
4  DeepPavlov/clinc150               nomic-ai/nomic-embed-text-v1.5  0.755273

In [6]:
df_new = pd.pivot_table(df, values="metrics", columns="dataset", index="encoder")
df_new.reset_index(inplace=True)
df_new

dataset,encoder,DeepPavlov/clinc150,DeepPavlov/hwu64,DeepPavlov/massive,DeepPavlov/minds14,DeepPavlov/snips
0,HIT-TMG/KaLM-embedding-multilingual-mini-v1,0.788545,0.886617,0.835916,0.953704,0.974286
1,NovaSearch/stella_en_400M_v5,0.918000,0.921933,0.892183,0.962963,0.985000
2,intfloat/multilingual-e5-large,0.787091,0.913569,0.874663,0.925926,0.983571
3,intfloat/multilingual-e5-large-instruct,0.789818,0.909851,0.871294,0.981481,0.983571
4,nomic-ai/nomic-embed-text-v1.5,0.755273,0.838290,0.806941,0.972222,0.973571

In [7]:
df_new["average"] = df_new.drop(columns=["encoder"]).mean(axis=1)
df_new

dataset,encoder,DeepPavlov/clinc150,DeepPavlov/hwu64,DeepPavlov/massive,DeepPavlov/minds14,DeepPavlov/snips,average
0,HIT-TMG/KaLM-embedding-multilingual-mini-v1,0.788545,0.886617,0.835916,0.953704,0.974286,0.887814
1,NovaSearch/stella_en_400M_v5,0.918000,0.921933,0.892183,0.962963,0.985000,0.936016
2,intfloat/multilingual-e5-large,0.787091,0.913569,0.874663,0.925926,0.983571,0.896964
3,intfloat/multilingual-e5-large-instruct,0.789818,0.909851,0.871294,0.981481,0.983571,0.907203
4,nomic-ai/nomic-embed-text-v1.5,0.755273,0.838290,0.806941,0.972222,0.973571,0.869259

In [8]:
df_new.sort_values(by="average", ascending=False)

dataset,encoder,DeepPavlov/clinc150,DeepPavlov/hwu64,DeepPavlov/massive,DeepPavlov/minds14,DeepPavlov/snips,average
1,NovaSearch/stella_en_400M_v5,0.918000,0.921933,0.892183,0.962963,0.985000,0.936016
3,intfloat/multilingual-e5-large-instruct,0.789818,0.909851,0.871294,0.981481,0.983571,0.907203
2,intfloat/multilingual-e5-large,0.787091,0.913569,0.874663,0.925926,0.983571,0.896964
0,HIT-TMG/KaLM-embedding-multilingual-mini-v1,0.788545,0.886617,0.835916,0.953704,0.974286,0.887814
4,nomic-ai/nomic-embed-text-v1.5,0.755273,0.838290,0.806941,0.972222,0.973571,0.869259

In [9]:
df_new = df_new.apply(lambda x: x * 100 if x.dtype == float else x)
df_new

dataset,encoder,DeepPavlov/clinc150,DeepPavlov/hwu64,DeepPavlov/massive,DeepPavlov/minds14,DeepPavlov/snips,average
0,HIT-TMG/KaLM-embedding-multilingual-mini-v1,78.854545,88.661710,83.591644,95.370370,97.428571,88.781368
1,NovaSearch/stella_en_400M_v5,91.800000,92.193309,89.218329,96.296296,98.500000,93.601587
2,intfloat/multilingual-e5-large,78.709091,91.356877,87.466307,92.592593,98.357143,89.696402
3,intfloat/multilingual-e5-large-instruct,78.981818,90.985130,87.129380,98.148148,98.357143,90.720324
4,nomic-ai/nomic-embed-text-v1.5,75.527273,83.828996,80.694070,97.222222,97.357143,86.925941

In [10]:
pd.set_option("display.precision", 2)

In [12]:
print(df_new.sort_values(by="average", ascending=False).to_string(index=False))

                                    encoder  DeepPavlov/clinc150  DeepPavlov/hwu64  DeepPavlov/massive  DeepPavlov/minds14  DeepPavlov/snips  average
               NovaSearch/stella_en_400M_v5                91.80             92.19               89.22               96.30             98.50    93.60
    intfloat/multilingual-e5-large-instruct                78.98             90.99               87.13               98.15             98.36    90.72
             intfloat/multilingual-e5-large                78.71             91.36               87.47               92.59             98.36    89.70
HIT-TMG/KaLM-embedding-multilingual-mini-v1                78.85             88.66               83.59               95.37             97.43    88.78
             nomic-ai/nomic-embed-text-v1.5                75.53             83.83               80.69               97.22             97.36    86.93