In [2]:
import json
from pathlib import Path

filepath = Path("framework_comparison.jsonl")
records = []
for line in filepath.open():
    records.append(json.loads(line))
len(records)

25

In [4]:
import pandas as pd

df = pd.DataFrame(records)
df.head()
df.columns

Index(['run_id', 'run_name', 'created_at', 'config.dataset',
       'config.framework', 'accuracy', 'macro_avg.f1-score',
       'macro_avg.precision', 'macro_avg.recall', 'macro_avg.support',
       'weighted_avg.f1-score', 'weighted_avg.precision',
       'weighted_avg.recall', 'weighted_avg.support'],
      dtype='object')

In [5]:
cols_to_drop = ["run_id", "run_name", "created_at"]
df = df.drop(columns=cols_to_drop)
df

,config.dataset,config.framework,accuracy,macro_avg.f1-score,macro_avg.precision,macro_avg.recall,macro_avg.support,weighted_avg.f1-score,weighted_avg.precision,weighted_avg.recall,weighted_avg.support
0,DeepPavlov/clinc150,fedot,0.181818,0.002038,0.001204,0.006623,5500,0.055944,0.033058,0.181818,5500
1,DeepPavlov/hwu64,fedot,0.017658,0.000542,0.000276,0.015625,1076,0.000613,0.000312,0.017658,1076
2,DeepPavlov/snips,fedot,0.151429,0.052631,0.449156,0.151429,1400,0.052631,0.449156,0.151429,1400
3,DeepPavlov/minds14,fedot,0.120370,0.080231,0.231848,0.106151,108,0.087636,0.247341,0.120370,108
4,DeepPavlov/massive,fedot,0.072776,0.004057,0.084553,0.018142,2968,0.013965,0.233475,0.072776,2968
5,DeepPavlov/banking77,fedot,0.012987,0.000333,0.000169,0.012987,3080,0.000333,0.000169,0.012987,3080
6,DeepPavlov/clinc150,glueon,0.873455,0.913901,0.876267,0.963700,5500,0.861773,0.894271,0.873455,5500
7,DeepPavlov/hwu64,glueon,0.911710,0.910216,0.908849,0.918053,1076,0.910096,0.913318,0.911710,1076
8,DeepPavlov/snips,glueon,0.990714,0.990721,0.990813,0.990714,1400,0.990721,0.990813,0.990714,1400
9,DeepPavlov/massive,glueon,0.889151,0.877618,0.873620,0.892717,2968,0.888104,0.890377,0.889151,2968
10,DeepPavlov/banking77,glueon,0.932792,0.932744,0.934953,0.932792,3080,0.932744,0.934953,0.932792,3080
11,DeepPavlov/minds14,glueon,0.972222,0.970050,0.975000,0.970663,108,0.971231,0.975463,0.972222,108
12,DeepPavlov/clinc150,h2o,0.663091,0.712536,0.680751,0.766748,5500,0.638623,0.704187,0.663091,5500
13,DeepPavlov/massive,h2o,0.753032,0.701375,0.731363,0.696775,2968,0.752438,0.758373,0.753032,2968
14,DeepPavlov/minds14,h2o,0.768519,0.759381,0.771331,0.766015,108,0.763690,0.776506,0.768519,108
15,DeepPavlov/snips,h2o,0.983571,0.983613,0.983833,0.983571,1400,0.983613,0.983833,0.983571,1400
16,DeepPavlov/hwu64,h2o,0.773234,0.762991,0.768144,0.768756,1076,0.769486,0.774684,0.773234,1076
17,DeepPavlov/banking77,h2o,0.752922,0.752755,0.761596,0.752922,3080,0.752755,0.761596,0.752922,3080
18,DeepPavlov/banking77,h2o,0.753571,0.753394,0.761347,0.753571,3080,0.753394,0.761347,0.753571,3080
19,DeepPavlov/clinc150,lama,0.181818,0.002038,0.001204,0.006623,5500,0.055944,0.033058,0.181818,5500
20,DeepPavlov/banking77,lama,0.012987,0.000333,0.000169,0.012987,3080,0.000333,0.000169,0.012987,3080
21,DeepPavlov/minds14,lama,0.083333,0.025898,0.076819,0.080357,108,0.026857,0.079665,0.083333,108
22,DeepPavlov/snips,lama,0.145000,0.040005,0.127609,0.145000,1400,0.040005,0.127609,0.145000,1400
23,DeepPavlov/hwu64,lama,0.017658,0.000542,0.000276,0.015625,1076,0.000613,0.000312,0.017658,1076
24,DeepPavlov/massive,lama,0.070418,0.002268,0.001214,0.017241,2968,0.009265,0.004959,0.070418,2968

In [18]:
pd.set_option("display.precision", 2)

In [26]:
accuracy_df = pd.pivot_table(df, index="config.framework", columns="config.dataset", values="accuracy")
accuracy_df["average"] = accuracy_df.mean(axis=1)
accuracy_df.sort_values(by="average", ascending=False, inplace=True)
accuracy_df *= 100
accuracy_df.reset_index(inplace=True)
accuracy_df

config.dataset,config.framework,DeepPavlov/banking77,DeepPavlov/clinc150,DeepPavlov/hwu64,DeepPavlov/massive,DeepPavlov/minds14,DeepPavlov/snips,average
0,glueon,93.28,87.35,91.17,88.92,97.22,99.07,92.83
1,h2o,75.32,66.31,77.32,75.30,76.85,98.36,78.24
2,fedot,1.30,18.18,1.77,7.28,12.04,15.14,9.28
3,lama,1.30,18.18,1.77,7.04,8.33,14.50,8.52

In [28]:
print(accuracy_df.to_string(index=False))

config.framework  DeepPavlov/banking77  DeepPavlov/clinc150  DeepPavlov/hwu64  DeepPavlov/massive  DeepPavlov/minds14  DeepPavlov/snips  average
          glueon                 93.28                87.35             91.17               88.92               97.22             99.07    92.83
             h2o                 75.32                66.31             77.32               75.30               76.85             98.36    78.24
           fedot                  1.30                18.18              1.77                7.28               12.04             15.14     9.28
            lama                  1.30                18.18              1.77                7.04                8.33             14.50     8.52

In [30]:
print(accuracy_df["DeepPavlov/clinc150"].to_string(index=False))

87.35
66.31
18.18
18.18

In [24]:
import json
from pathlib import Path

savepath = Path("wandb_oos/AutoML-Eval/results.json")
with savepath.open() as file:
    data = json.load(file)["null"]

In [25]:
cols = ["in_domain_acc", "oos_precision", "oos_recall"]
rows = []
for res in data:
    frame = res["config"].get("framework", None)
    if frame is None:
        continue
    frame = frame["value"]
    metrics = {"framework": frame}
    for metric_name, metrics_dict in res["wandb-summary"].items():
        if metric_name not in cols:
            continue
        metrics[metric_name] = metrics_dict
    rows.append(metrics)
rows

[{'framework': 'gluon',
  'in_domain_acc': 0.9575555555555556,
  'oos_precision': 0.9847094801223242,
  'oos_recall': 0.322},
 {'framework': 'fedot',
  'in_domain_acc': 0,
  'oos_recall': 1,
  'oos_precision': 0.18181818181818182},
 {'framework': 'lama',
  'in_domain_acc': 0,
  'oos_precision': 0.18181818181818182,
  'oos_recall': 1},
 {'framework': 'h2o',
  'oos_precision': 0.8256880733944955,
  'oos_recall': 0.27,
  'in_domain_acc': 0.8522222222222222}]

In [26]:
import pandas as pd

df = pd.DataFrame(rows)
pd.set_option("display.precision", 2)
df[cols] *= 100
print(df.to_string(index=False))

framework  in_domain_acc  oos_precision  oos_recall
    gluon          95.76          98.47        32.2
    fedot           0.00          18.18       100.0
     lama           0.00          18.18       100.0
      h2o          85.22          82.57        27.0

[{'module_name': 'eval-DeepPavlov/clinc150-gluon-gluon-medium-quality-no-hpo',
  'config': {'dataset': {'value': 'DeepPavlov/clinc150'},
   'framework': {'value': 'gluon'}},
  'wandb-summary': {'110.0': {'precision': 0.8529411764705882,
    'recall': 0.9666666666666667,
    'f1-score': 0.90625,
    'support': 30},
   '117.0': {'recall': 1,
    'f1-score': 0.9836065573770492,
    'support': 30,
    'precision': 0.967741935483871},
   '86.0': {'f1-score': 0.7058823529411765,
    'support': 30,
    'precision': 0.631578947368421,
    'recall': 0.8},
   '118.0': {'f1-score': 0.9523809523809523,
    'support': 30,
    'precision': 0.9090909090909091,
    'recall': 1},
   '69.0': {'f1-score': 0.9830508474576272,
    'support': 30,
    'precision': 1,
    'recall': 0.9666666666666667},
   '75.0': {'recall': 1,
    'f1-score': 0.9523809523809523,
    'support': 30,
    'precision': 0.9090909090909091},
   '47.0': {'precision': 0.8333333333333334,
    'recall': 1,
    'f1-score': 0.9090909090909091,
    'support': 30},
   '124.0': {'recall': 1,
    'f1-score': 0.9375,
    'support': 30,
    'precision': 0.8823529411764706},
   '_timestamp': 1747869583.3816907,
   '133.0': {'precision': 0.9642857142857143,
    'recall': 0.9,
    'f1-score': 0.9310344827586207,
    'support': 30},
   '55.0': {'f1-score': 0.8955223880597015,
    'support': 30,
    'precision': 0.8108108108108109,
    'recall': 1},
   '44.0': {'f1-score': 0.9508196721311475,
    'support': 30,
    'precision': 0.9354838709677419,
    'recall': 0.9666666666666667},
   '24.0': {'support': 30,
    'precision': 0.8823529411764706,
    'recall': 1,
    'f1-score': 0.9375},
   '51.0': {'support': 30,
    'precision': 0.7428571428571429,
    'recall': 0.8666666666666667,
    'f1-score': 0.8},
   '127.0': {'f1-score': 0.9230769230769231,
    'support': 30,
    'precision': 0.8571428571428571,
    'recall': 1},
   '103.0': {'support': 30,
    'precision': 0.6590909090909091,
    'recall': 0.9666666666666667,
    'f1-score': 0.7837837837837838},
   '22.0': {'precision': 0.8333333333333334,
    'recall': 1,
    'f1-score': 0.9090909090909091,
    'support': 30},
   '136.0': {'recall': 1,
    'f1-score': 0.8571428571428571,
    'support': 30,
    'precision': 0.75},
   'predictions': {'size': 45723,
    'artifact_path': 'wandb-client-artifact://6bllmbd26d9zd6bb5qmda8tebknkbbqbja1rbe1qdqmqt1adrl6k961m0840bmmf9fvbykn1pmadc3s2sev94w999vx80dde11at07gc0xw6hzgtlippbg2q8czd0825/predictions.table.json',
    '_latest_artifact_path': 'wandb-client-artifact://uabu7470qke5p9a4njfrraxtsmvyiivlrvt2x73mnj5ofo1ju3ppd3qioj3cgwqu8knoupfk0xipqj8nei4lz10xvlv4l0o73v7wbeu87kn25syp9t39q8qmjt4eb27n:latest/predictions.table.json',
    'path': 'media/table/predictions_0_9d920b7dee3403ef9526.table.json',
    'ncols': 1,
    'nrows': 5500,
    '_type': 'table-file',
    'sha256': '9d920b7dee3403ef9526bbd91f40c1fff5a109dd880d08153e0ed0b605cc9d09'},
   '77.0': {'precision': 0.5172413793103449,
    'recall': 1,
    'f1-score': 0.6818181818181818,
    'support': 30},
   '61.0': {'recall': 0.9666666666666667,
    'f1-score': 0.9830508474576272,
    'support': 30,
    'precision': 1},
   '134.0': {'support': 30,
    'precision': 0.6829268292682927,
    'recall': 0.9333333333333333,
    'f1-score': 0.7887323943661971},
   '90.0': {'precision': 0.8787878787878788,
    'recall': 0.9666666666666667,
    'f1-score': 0.9206349206349206,
    'support': 30},
   '126.0': {'f1-score': 0.9354838709677419,
    'support': 30,
    'precision': 0.90625,
    'recall': 0.9666666666666667},
   '114.0': {'f1-score': 0.90625,
    'support': 30,
    'precision': 0.8529411764705882,
    'recall': 0.9666666666666667},
   '41.0': {'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871,
    'support': 30},
   '_step': 2,
   '137.0': {'precision': 0.9666666666666667,
    'recall': 0.9666666666666667,
    'f1-score': 0.9666666666666667,
    'support': 30},
   '82.0': {'precision': 0.8484848484848485,
    'recall': 0.9333333333333333,
    'f1-score': 0.8888888888888888,
    'support': 30},
   '80.0': {'recall': 0.8666666666666667,
    'f1-score': 0.65,
    'support': 30,
    'precision': 0.52},
   '94.0': {'support': 30,
    'precision': 0.8529411764705882,
    'recall': 0.9666666666666667,
    'f1-score': 0.90625},
   '141.0': {'recall': 1,
    'f1-score': 0.9375,
    'support': 30,
    'precision': 0.8823529411764706},
   '66.0': {'support': 30,
    'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871},
   '71.0': {'support': 30,
    'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871},
   '123.0': {'f1-score': 0.9508196721311475,
    'support': 30,
    'precision': 0.9354838709677419,
    'recall': 0.9666666666666667},
   '42.0': {'f1-score': 0.9375,
    'support': 30,
    'precision': 0.8823529411764706,
    'recall': 1},
   '40.0': {'support': 30,
    'precision': 0.90625,
    'recall': 0.9666666666666667,
    'f1-score': 0.9354838709677419},
   '112.0': {'recall': 0.9666666666666667,
    'f1-score': 0.9666666666666667,
    'support': 30,
    'precision': 0.9666666666666667},
   '13.0': {'precision': 0.875,
    'recall': 0.9333333333333333,
    'f1-score': 0.9032258064516129,
    'support': 30},
   '129.0': {'precision': 0.9285714285714286,
    'recall': 0.8666666666666667,
    'f1-score': 0.896551724137931,
    'support': 30},
   '30.0': {'precision': 1,
    'recall': 0.9666666666666667,
    'f1-score': 0.9830508474576272,
    'support': 30},
   '49.0': {'recall': 0.8333333333333334,
    'f1-score': 0.8333333333333334,
    'support': 30,
    'precision': 0.8333333333333334},
   'in_domain_acc': 0.9575555555555556,
   '101.0': {'f1-score': 0.8387096774193549,
    'support': 30,
    'precision': 0.8125,
    'recall': 0.8666666666666667},
   '45.0': {'support': 30,
    'precision': 0.7692307692307693,
    'recall': 1,
    'f1-score': 0.8695652173913043},
   '143.0': {'f1-score': 0.9032258064516129,
    'support': 30,
    'precision': 0.875,
    'recall': 0.9333333333333333},
   '25.0': {'support': 30,
    'precision': 0.7222222222222222,
    'recall': 0.8666666666666667,
    'f1-score': 0.7878787878787878},
   '140.0': {'recall': 1,
    'f1-score': 0.8,
    'support': 30,
    'precision': 0.6666666666666666},
   '115.0': {'recall': 0.9333333333333333,
    'f1-score': 0.7466666666666667,
    'support': 30,
    'precision': 0.6222222222222222},
   '1.0': {'recall': 0.9666666666666667,
    'f1-score': 0.8055555555555556,
    'support': 30,
    'precision': 0.6904761904761905},
   '8.0': {'precision': 0.7567567567567568,
    'recall': 0.9333333333333333,
    'f1-score': 0.835820895522388,
    'support': 30},
   '5.0': {'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871,
    'support': 30},
   '146.0': {'recall': 1,
    'f1-score': 0.9523809523809523,
    'support': 30,
    'precision': 0.9090909090909091},
   '56.0': {'f1-score': 0.7323943661971831,
    'support': 30,
    'precision': 0.6341463414634146,
    'recall': 0.8666666666666667},
   '131.0': {'precision': 0.875,
    'recall': 0.9333333333333333,
    'f1-score': 0.9032258064516129,
    'support': 30},
   '83.0': {'precision': 0.9655172413793104,
    'recall': 0.9333333333333333,
    'f1-score': 0.9491525423728814,
    'support': 30},
   '148.0': {'recall': 1,
    'f1-score': 0.8955223880597015,
    'support': 30,
    'precision': 0.8108108108108109},
   'oos_precision': 0.9847094801223242,
   '50.0': {'precision': 0.8055555555555556,
    'recall': 0.9666666666666667,
    'f1-score': 0.8787878787878788,
    'support': 30},
   '10.0': {'recall': 1,
    'f1-score': 0.8823529411764706,
    'support': 30,
    'precision': 0.7894736842105263},
   '95.0': {'recall': 0.8666666666666667,
    'f1-score': 0.8524590163934426,
    'support': 30,
    'precision': 0.8387096774193549},
   '11.0': {'recall': 0.9333333333333333,
    'f1-score': 0.9032258064516129,
    'support': 30,
    'precision': 0.875},
   '63.0': {'precision': 0.9090909090909091,
    'recall': 1,
    'f1-score': 0.9523809523809523,
    'support': 30},
   '39.0': {'f1-score': 0.9375,
    'support': 30,
    'precision': 0.8823529411764706,
    'recall': 1},
   '62.0': {'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871,
    'support': 30},
   '135.0': {'f1-score': 0.9230769230769231,
    'support': 30,
    'precision': 0.8571428571428571,
    'recall': 1},
   '96.0': {'f1-score': 0.9333333333333333,
    'support': 30,
    'precision': 0.9333333333333333,
    'recall': 0.9333333333333333},
   'macro avg': {'recall': 0.9533465783664459,
    'f1-score': 0.8925933877391569,
    'support': 5500,
    'precision': 0.8484061272478143},
   '132.0': {'f1-score': 0.9206349206349206,
    'support': 30,
    'precision': 0.8787878787878788,
    'recall': 0.9666666666666667},
   '16.0': {'precision': 0.8571428571428571,
    'recall': 1,
    'f1-score': 0.9230769230769231,
    'support': 30},
   '93.0': {'f1-score': 0.8771929824561403,
    'support': 30,
    'precision': 0.9259259259259259,
    'recall': 0.8333333333333334},
   'weighted avg': {'recall': 0.842,
    'f1-score': 0.8207625618483619,
    'support': 5500,
    'precision': 0.8724450822093187},
   '18.0': {'f1-score': 0.8888888888888888,
    'support': 30,
    'precision': 1,
    'recall': 0.8},
   '35.0': {'recall': 1,
    'f1-score': 0.9230769230769231,
    'support': 30,
    'precision': 0.8571428571428571},
   '73.0': {'f1-score': 0.8529411764705882,
    'support': 30,
    'precision': 0.7631578947368421,
    'recall': 0.9666666666666667},
   '3.0': {'precision': 0.9090909090909091,
    'recall': 1,
    'f1-score': 0.9523809523809523,
    'support': 30},
   '46.0': {'f1-score': 0.8923076923076924,
    'support': 30,
    'precision': 0.8285714285714286,
    'recall': 0.9666666666666667},
   '91.0': {'recall': 0.9333333333333333,
    'f1-score': 0.9032258064516129,
    'support': 30,
    'precision': 0.875},
   '_runtime': 2474.372029973,
   '74.0': {'recall': 0.9666666666666667,
    'f1-score': 0.8285714285714286,
    'support': 30,
    'precision': 0.725},
   '145.0': {'f1-score': 0.9032258064516129,
    'support': 30,
    'precision': 0.875,
    'recall': 0.9333333333333333},
   '87.0': {'f1-score': 0.8615384615384616,
    'support': 30,
    'precision': 0.8,
    'recall': 0.9333333333333333},
   'accuracy': 0.842,
   '20.0': {'recall': 1,
    'f1-score': 0.9836065573770492,
    'support': 30,
    'precision': 0.967741935483871},
   '6.0': {'recall': 0.9666666666666667,
    'f1-score': 0.90625,
    'support': 30,
    'precision': 0.8529411764705882},
   '72.0': {'f1-score': 0.8450704225352113,
    'support': 30,
    'precision': 0.7317073170731707,
    'recall': 1},
   '26.0': {'support': 30, 'precision': 1, 'recall': 1, 'f1-score': 1},
   '150.0': {'precision': 0.9847094801223242,
    'recall': 0.322,
    'f1-score': 0.4853051996985682,
    'support': 1000},
   '98.0': {'precision': 0.8235294117647058,
    'recall': 0.9333333333333333,
    'f1-score': 0.875,
    'support': 30},
   '138.0': {'f1-score': 0.9230769230769231,
    'support': 30,
    'precision': 0.8571428571428571,
    'recall': 1},
   '79.0': {'precision': 0.9, 'recall': 0.9, 'f1-score': 0.9, 'support': 30},
   '12.0': {'precision': 0.8387096774193549,
    'recall': 0.8666666666666667,
    'f1-score': 0.8524590163934426,
    'support': 30},
   '125.0': {'support': 30,
    'precision': 0.8823529411764706,
    'recall': 1,
    'f1-score': 0.9375},
   '31.0': {'recall': 0.9333333333333333,
    'f1-score': 0.9180327868852459,
    'support': 30,
    'precision': 0.9032258064516129},
   '121.0': {'support': 30,
    'precision': 0.9642857142857143,
    'recall': 0.9,
    'f1-score': 0.9310344827586207},
   '21.0': {'precision': 0.8484848484848485,
    'recall': 0.9333333333333333,
    'f1-score': 0.8888888888888888,
    'support': 30},
   '144.0': {'recall': 1,
    'f1-score': 0.9090909090909091,
    'support': 30,
    'precision': 0.8333333333333334},
   '70.0': {'precision': 0.8333333333333334,
    'recall': 1,
    'f1-score': 0.9090909090909091,
    'support': 30},
   '19.0': {'f1-score': 0.9508196721311475,
    'support': 30,
    'precision': 0.9354838709677419,
    'recall': 0.9666666666666667},
   '84.0': {'precision': 0.9310344827586207,
    'recall': 0.9,
    'f1-score': 0.9152542372881356,
    'support': 30},
   '92.0': {'support': 30,
    'precision': 0.4166666666666667,
    'recall': 0.8333333333333334,
    'f1-score': 0.5555555555555556},
   '59.0': {'recall': 0.9666666666666667,
    'f1-score': 0.9206349206349206,
    'support': 30,
    'precision': 0.8787878787878788},
   '108.0': {'support': 30,
    'precision': 0.717948717948718,
    'recall': 0.9333333333333333,
    'f1-score': 0.8115942028985508},
   '111.0': {'recall': 0.9666666666666667,
    'f1-score': 0.8787878787878788,
    'support': 30,
    'precision': 0.8055555555555556},
   '88.0': {'precision': 0.9354838709677419,
    'recall': 0.9666666666666667,
    'f1-score': 0.9508196721311475,
    'support': 30},
   '37.0': {'support': 30,
    'precision': 0.6756756756756757,
    'recall': 0.8333333333333334,
    'f1-score': 0.746268656716418},
   '97.0': {'support': 30,
    'precision': 0.8125,
    'recall': 0.8666666666666667,
    'f1-score': 0.8387096774193549},
   '0.0': {'f1-score': 0.8571428571428571,
    'support': 30,
    'precision': 0.8181818181818182,
    'recall': 0.9},
   '120.0': {'recall': 0.9,
    'f1-score': 0.8709677419354839,
    'support': 30,
    'precision': 0.84375},
   '53.0': {'precision': 0.7692307692307693,
    'recall': 1,
    'f1-score': 0.8695652173913043,
    'support': 30},
   '122.0': {'recall': 0.9666666666666667,
    'f1-score': 0.9508196721311475,
    'support': 30,
    'precision': 0.9354838709677419},
   '48.0': {'f1-score': 0.9354838709677419,
    'support': 30,
    'precision': 0.90625,
    'recall': 0.9666666666666667},
   '_wandb': {'runtime': 2474},
   '9.0': {'recall': 0.9666666666666667,
    'f1-score': 0.9666666666666667,
    'support': 30,
    'precision': 0.9666666666666667},
   '78.0': {'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871,
    'support': 30},
   '107.0': {'support': 30,
    'precision': 0.8823529411764706,
    'recall': 1,
    'f1-score': 0.9375},
   '58.0': {'support': 30,
    'precision': 0.6744186046511628,
    'recall': 0.9666666666666667,
    'f1-score': 0.7945205479452054},
   '106.0': {'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871,
    'support': 30},
   '28.0': {'f1-score': 0.9090909090909091,
    'support': 30,
    'precision': 0.8333333333333334,
    'recall': 1},
   '68.0': {'support': 30,
    'precision': 0.9354838709677419,
    'recall': 0.9666666666666667,
    'f1-score': 0.9508196721311475},
   '38.0': {'precision': 0.75,
    'recall': 1,
    'f1-score': 0.8571428571428571,
    'support': 30},
   '17.0': {'f1-score': 0.9523809523809523,
    'support': 30,
    'precision': 0.9090909090909091,
    'recall': 1},
   '52.0': {'precision': 0.8823529411764706,
    'recall': 1,
    'f1-score': 0.9375,
    'support': 30},
   '81.0': {'f1-score': 0.967741935483871,
    'support': 30,
    'precision': 0.9375,
    'recall': 1},
   '100.0': {'f1-score': 1, 'support': 30, 'precision': 1, 'recall': 1},
   'oos_recall': 0.322,
   '147.0': {'support': 30,
    'precision': 0.8333333333333334,
    'recall': 0.8333333333333334,
    'f1-score': 0.8333333333333334},
   '23.0': {'recall': 1,
    'f1-score': 0.967741935483871,
    'support': 30,
    'precision': 0.9375},
   '27.0': {'support': 30,
    'precision': 0.7631578947368421,
    'recall': 0.9666666666666667,
    'f1-score': 0.8529411764705882},
   '7.0': {'support': 30,
    'precision': 0.8518518518518519,
    'recall': 0.7666666666666667,
    'f1-score': 0.8070175438596491},
   '119.0': {'support': 30,
    'precision': 0.7567567567567568,
    'recall': 0.9333333333333333,
    'f1-score': 0.835820895522388},
   '128.0': {'recall': 1,
    'f1-score': 0.9090909090909091,
    'support': 30,
    'precision': 0.8333333333333334},
   '65.0': {'support': 30,
    'precision': 0.7073170731707317,
    'recall': 0.9666666666666667,
    'f1-score': 0.8169014084507042},
   '43.0': {'support': 30,
    'precision': 0.9090909090909091,
    'recall': 1,
    'f1-score': 0.9523809523809523},
   '89.0': {'support': 30,
    'precision': 0.8484848484848485,
    'recall': 0.9333333333333333,
    'f1-score': 0.8888888888888888},
   '2.0': {'f1-score': 0.967741935483871,
    'support': 30,
    'precision': 0.9375,
    'recall': 1},
   '102.0': {'support': 30,
    'precision': 0.7631578947368421,
    'recall': 0.9666666666666667,
    'f1-score': 0.8529411764705882},
   '105.0': {'precision': 0.967741935483871,
    'recall': 1,
    'f1-score': 0.9836065573770492,
    'support': 30},
   '36.0': {'precision': 0.6, 'recall': 1, 'f1-score': 0.75, 'support': 30},
   '116.0': {'f1-score': 0.8571428571428571,
    'support': 30,
    'precision': 0.75,
    'recall': 1},
   '130.0': {'f1-score': 0.9310344827586207,
    'support': 30,
    'precision': 0.9642857142857143,
    'recall': 0.9},
   '139.0': {'precision': 0.967741935483871,
    'recall': 1,
    'f1-score': 0.9836065573770492,
    'support': 30},
   '60.0': {'precision': 0.8108108108108109,
    'recall': 1,
    'f1-score': 0.8955223880597015,
    'support': 30},
   '33.0': {'support': 30,
    'precision': 0.8787878787878788,
    'recall': 0.9666666666666667,
    'f1-score': 0.9206349206349206},
   '99.0': {'precision': 0.9655172413793104,
    'recall': 0.9333333333333333,
    'f1-score': 0.9491525423728814,
    'support': 30},
   '32.0': {'precision': 0.75,
    'recall': 1,
    'f1-score': 0.8571428571428571,
    'support': 30},
   '85.0': {'support': 30,
    'precision': 0.8108108108108109,
    'recall': 1,
    'f1-score': 0.8955223880597015},
   '104.0': {'recall': 1,
    'f1-score': 0.8571428571428571,
    'support': 30,
    'precision': 0.75},
   '14.0': {'f1-score': 0.8450704225352113,
    'support': 30,
    'precision': 0.7317073170731707,
    'recall': 1},
   '76.0': {'recall': 1, 'f1-score': 1, 'support': 30, 'precision': 1},
   '113.0': {'f1-score': 0.835820895522388,
    'support': 30,
    'precision': 0.7567567567567568,
    'recall': 0.9333333333333333},
   '4.0': {'precision': 0.9090909090909091,
    'recall': 1,
    'f1-score': 0.9523809523809523,
    'support': 30},
   '29.0': {'recall': 0.9666666666666667,
    'f1-score': 0.9508196721311475,
    'support': 30,
    'precision': 0.9354838709677419},
   '34.0': {'support': 30,
    'precision': 0.6590909090909091,
    'recall': 0.9666666666666667,
    'f1-score': 0.7837837837837838},
   '142.0': {'support': 30,
    'precision': 0.9354838709677419,
    'recall': 0.9666666666666667,
    'f1-score': 0.9508196721311475},
   '149.0': {'support': 30,
    'precision': 0.9583333333333334,
    'recall': 0.7666666666666667,
    'f1-score': 0.8518518518518519},
   '15.0': {'recall': 0.9666666666666667,
    'f1-score': 0.8656716417910447,
    'support': 30,
    'precision': 0.7837837837837838},
   '54.0': {'precision': 0.8108108108108109,
    'recall': 1,
    'f1-score': 0.8955223880597015,
    'support': 30},
   '67.0': {'precision': 0.7297297297297297,
    'recall': 0.9,
    'f1-score': 0.8059701492537313,
    'support': 30},
   '57.0': {'precision': 0.8571428571428571,
    'recall': 1,
    'f1-score': 0.9230769230769231,
    'support': 30},
   '64.0': {'recall': 1,
    'f1-score': 0.9230769230769231,
    'support': 30,
    'precision': 0.8571428571428571},
   '109.0': {'precision': 0.9375,
    'recall': 1,
    'f1-score': 0.967741935483871,
    'support': 30}}},
 {'module_name': 'eval-DeepPavlov/clinc150-fedot-halo',
  'config': {'dataset': {'value': 'DeepPavlov/clinc150'},
   'framework': {'value': 'fedot'}},
  'wandb-summary': {'59.0': {'f1-score': 0,
    'support': 30,
    'precision': 0,
    'recall': 0},
   '84.0': {'support': 30, 'precision': 0, 'recall': 0, 'f1-score': 0},